version: '3'

services:
  database:
    image: 'postgres:14.3'
    restart: always
    ports:
      - 15432:5432
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data/
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - pgadmin:/var/lib/pgadmin/

volumes:
    database:
    pgadmin: