# Use root/example as user/password credentials
version: '3'

services:
  db:
    restart: always
    image: postgre:latest
    build:
      dockerfile: docker/Dockerfile
        target: $ENVIRONMENT
          args:
            POSTGRES_USER=${POSTGRES_USER} 
            POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
            POSTGRES_DB=${POSTGRES_DB}
    ports:
        - "5432:5432"
    env_file:
        - .env
    volumes: 
          - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local