version: '3.8'

services:
  database:
    image: 'postgres:14.3'
    restart: always
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - database:/var/lib/postgresql/data/
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - pgadmin:/var/lib/pgadmin/

  python:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - database
    networks:
      - postgres-network    
    
volumes:
    database:
    pgadmin:

networks: 
  postgres-network: